services:
  python:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .dockervenv:/src/.venv
      - .:/src

  database:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'main'
      TZ: 'Asia/Tokyo'
    ports:
      - 33306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: